//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayscoutIcon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string serverUrl {
            get {
                return ((string)(this["serverUrl"]));
            }
            set {
                this["serverUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string apiSecretSha1 {
            get {
                return ((string)(this["apiSecretSha1"]));
            }
            set {
                this["apiSecretSha1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public double updateInterval {
            get {
                return ((double)(this["updateInterval"]));
            }
            set {
                this["updateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12000")]
        public int networkTimeout {
            get {
                return ((int)(this["networkTimeout"]));
            }
            set {
                this["networkTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public int durationDNSCache {
            get {
                return ((int)(this["durationDNSCache"]));
            }
            set {
                this["durationDNSCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool alarmLow {
            get {
                return ((bool)(this["alarmLow"]));
            }
            set {
                this["alarmLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool alarmHigh {
            get {
                return ((bool)(this["alarmHigh"]));
            }
            set {
                this["alarmHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool alarmHigher {
            get {
                return ((bool)(this["alarmHigher"]));
            }
            set {
                this["alarmHigher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool alarmLower {
            get {
                return ((bool)(this["alarmLower"]));
            }
            set {
                this["alarmLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.0")]
        public decimal alarmBlglLow {
            get {
                return ((decimal)(this["alarmBlglLow"]));
            }
            set {
                this["alarmBlglLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0")]
        public decimal alarmBlglHigh {
            get {
                return ((decimal)(this["alarmBlglHigh"]));
            }
            set {
                this["alarmBlglHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.8")]
        public decimal alarmBlglLower {
            get {
                return ((decimal)(this["alarmBlglLower"]));
            }
            set {
                this["alarmBlglLower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int displayMmolDecimalsRouding {
            get {
                return ((int)(this["displayMmolDecimalsRouding"]));
            }
            set {
                this["displayMmolDecimalsRouding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int secondsGlucoseValueValid {
            get {
                return ((int)(this["secondsGlucoseValueValid"]));
            }
            set {
                this["secondsGlucoseValueValid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int bloodsugerUnitsIndex {
            get {
                return ((int)(this["bloodsugerUnitsIndex"]));
            }
            set {
                this["bloodsugerUnitsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disclaimerAgreed {
            get {
                return ((bool)(this["disclaimerAgreed"]));
            }
            set {
                this["disclaimerAgreed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool confirmExit {
            get {
                return ((bool)(this["confirmExit"]));
            }
            set {
                this["confirmExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool noHypoAlarmWarningShowed {
            get {
                return ((bool)(this["noHypoAlarmWarningShowed"]));
            }
            set {
                this["noHypoAlarmWarningShowed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showNightscoutTrayLink {
            get {
                return ((bool)(this["showNightscoutTrayLink"]));
            }
            set {
                this["showNightscoutTrayLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.9")]
        public decimal alarmBlglHigher {
            get {
                return ((decimal)(this["alarmBlglHigher"]));
            }
            set {
                this["alarmBlglHigher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTC")]
        public string timezone {
            get {
                return ((string)(this["timezone"]));
            }
            set {
                this["timezone"] = value;
            }
        }
    }
}
